# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

for f in ~/.aliases/*; do source $f; done
eval "$(direnv hook $0)"
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# ruby doesnt like gcc-4.2 anymore
export CC=/usr/bin/gcc


 #export REDISTOGO_URL for local
 export REDISTOGO_URL="http://127.0.0.1:6379"
 ## RVM Changing SUDO's Strict Defaults: https://rvm.io/integration/sudo
 export rvmsudo_secure_path=0

 # Don't correct me when I am right
#if [ -f ~/.zsh_nocorrect ]; then
  #while read -r COMMAND; do
    #alias $COMMAND="nocorrect $COMMAND"
  #done < ~/.zsh_nocorrect
#fi
#load zsh auto completion for aws cli
source /usr/local/share/zsh/site-functions/_aws
export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt
export BUNDLER_EDITOR=mvim
export EDITOR=mvim
export VISUAL=vim
export RBENV_ROOT=/usr/local/var/rbenv
export ANDROID_HOME=/usr/local/opt/android-sdk

source <(kubectl completion zsh)
# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# Now we can pipe to multiple outputs!
setopt MULTIOS

# This makes cd=pushd
setopt AUTO_PUSHD

# This will use named dirs when possible
setopt AUTO_NAME_DIRS

# If we have a glob this will expand it
setopt GLOB_COMPLETE
setopt PUSHD_MINUS

# No more annoying pushd messages...
# setopt PUSHD_SILENT

# blank pushd goes to home
setopt PUSHD_TO_HOME

# this will ignore multiple directories for the stack.  Useful?  I dunno.
setopt PUSHD_IGNORE_DUPS

# 10 second wait if you do something that will delete everything.  I wish I'd had this before...
setopt RM_STAR_WAIT

# use magic (this is default, but it can't hurt!)
setopt ZLE

setopt NO_HUP

setopt IGNORE_EOF

# If I could disable Ctrl-s completely I would!
setopt NO_FLOW_CONTROL

# Keep echo "station" > station from clobbering station
setopt NO_CLOBBER

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# I don't know why I never set this before.
setopt EXTENDED_GLOB

# hows about arrays be awesome?  (that is, frew${cool}frew has frew surrounding all the variables, not just first and last
setopt RC_EXPAND_PARAM

# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey "\eOP" run-help

# oh wow!  This is killer...  try it!
bindkey -M vicmd "q" push-line

# it's like, space AND completion.  Gnarlbot.
bindkey -M viins ' ' magic-space

# Add custom completions to fpath
fpath=(~/.completions $fpath)

# Initialize fasd
eval "$(fasd --init auto)"
# What the fuck??
alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
export ZSHRC_LOADED=true
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
# Customize to your needs...
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/Users/faraaz/usr/bin:/usr/local/Cellar/mysql55/5.5.44/bin:$GOPATH/bin
export GOPATH="/Users/faraaz/Developer/Go"
export GOROOT=$(go env GOROOT)
